name: Tag Create Testing

on:
  workflow_dispatch:

jobs:
  run-things:
    runs-on: ubuntu-latest
    steps:
      - name: Tag run
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.ref_name }}',
              sha: context.sha
            })
