# This is a basic workflow to help you get started with Actions

name: Dynamic runner

on:
  workflow_dispatch:
    inputs:
      runner-group:
        type: choice
        description: Runner Group
        options:
        - Physical
        - Virtual

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  find-runner:
    runs-on: ubuntu-latest

    outputs:
      runnerName: ${{ steps.find-instance.outputs.runnerName || 'self-hosted' }}

    steps:
    - name: Find an instance
      if: ${{ inputs.runner-group }} == 'Virtual'
      id: find-instance
      shell: pwsh
      run: |
        $runnerName = "self-hosted" # Just use any self-hosted runner available now

        # Actually look for one, and start it up

        echo "runnerName=$runnerName" >> $env:GITHUB_OUTPUT
        
  # This workflow contains a single job called "build"
  build:
    needs: [find-runner]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a thing
      shell: pwsh
      run: |
        $runnerName = ${{ needs.find-runner.outputs.runnerName || inputs.runner-group || 'fall back' }}
        echo "I would have run on $runnerName
