# This is a basic workflow to help you get started with Actions

name: Env test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Append Git info to Env
        shell: pwsh
        run: |
          git branch --show-current
          git rev-parse --short ${{ github.sha }}
        
      - name: Append Git info to Env
        shell: pwsh
        run: |
          echo "GitBranch=$(git branch --show-current)" >> $env:GITHUB_ENV
          echo "GitCommit=$(git rev-parse --short ${{ github.sha }})" >> $env:GITHUB_ENV
          echo "ALLCAPS=$(git rev-parse --short ${{ github.sha }})" >> $env:GITHUB_ENV

      - name: Use new Env
        shell: pwsh
        run: |
          Write-Host "Git Branch: $env:GITBRANCH"
          Write-Host "Git Commit: $env:GITCOMMIT"
          Write-Host "ALLCAPS: $env:ALLCAPS"
