
name: Inputs Testing

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true
      #   options:
      #     - development
      #     - staging
      #     - production

jobs:
  run-things:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        if: ${{ inputs.print_tags }} 
        run: echo  The tags are ${{ inputs.tags }}
      - name: Print the input environment to STDOUT
        run: echo  The environment is ${{ inputs.environment }}
      # - name: Print the input environment to STDOUT
      #   run: echo  The environment is ${{ inputs.environment }}
      - name: Print the input logLevel to STDOUT
        run: echo  The logLevel is ${{ inputs.logLevel }}

  
  tag:
    runs-on: ubuntu-latest
    needs: [ run-things ]
    # permissions:
    #   id-token: write
    #   contents: write
    #   repository-projects: write
    steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with:
    #         path: "./ChronoForge"
            
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/build/this-tagged',
              sha: context.sha
            })
