# This is a basic workflow to help you get started with Actions

name: Powershell Switch testing

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      run-switch:
        type: boolean
        description: Run Switch
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a script
        run: |
          Write-Host "./Script.ps1 `
          -Param1 $thing `
          ${{ inputs.run-switch && '-DoSwitch' || ''}} `
          "
