
name: Ref Input testing

on:
  workflow_dispatch:

jobs:
  run-things:
    runs-on: ubuntu-latest
    steps:
      - name: Print the running ref to STDOUT
        run: echo  The Ref is ${{ github.ref }}
      - name: Print the running ref name to STDOUT
        run: echo  The Ref Name is ${{ github.ref_name }}
      - name: Print the running ref type to STDOUT
        run: echo  The Ref Type is ${{ github.ref_type }}
